# -*- coding: utf-8 -*-
"""BuySell.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y94wCvVoo0F6lNErNEvezwtbr_GmlTr1
"""

import pandas as pd
import numpy as np

df = pd.read_csv('finalfew.csv')

for i in range(0,df.shape[0]-4):
    df.loc[df.index[i+2],'SMA_5'] = np.round(((df.iloc[i,2]+df.iloc[i+1,2]+df.iloc[i+2,2]+df.iloc[i+3,2]+df.iloc[i+4,2])/5),5)

df.plot()

df.to_csv('finalout.csv')

